In [9]:
import pandas as pd

In [17]:
diamond_db = pd.read_csv('../data/diamonds_train.csv')

In [18]:
diamond_db

       carat        cut color clarity  depth  table  price     x     y     z
0       1.21    Premium     J     VS2   62.4   58.0   4268  6.83  6.79  4.25
1       0.32  Very Good     H     VS2   63.0   57.0    505  4.35  4.38  2.75
2       0.71       Fair     G     VS1   65.5   55.0   2686  5.62  5.53  3.65
3       0.41       Good     D     SI1   63.8   56.0    738  4.68  4.72  3.00
4       1.02      Ideal     G     SI1   60.5   59.0   4882  6.55  6.51  3.95
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
40450   1.34      Ideal     G     VS1   62.7   57.0  10070  7.10  7.04  4.43
40451   2.02       Good     F     SI2   57.1   60.0  12615  8.31  8.25  4.73
40452   1.01      Ideal     H     SI1   62.7   56.0   5457  6.37  6.42  4.01
40453   0.33      Ideal     J     VS1   61.9   54.3    456  4.45  4.47  2.76
40454   1.24      Ideal     I     SI1   62.0   58.0   6232  6.83  6.88  4.25

[40455 rows x 10 columns]